# Backtest Configuration for my-quant-journal
# This file contains all the parameters needed to run backtests

# Backtesting Engine Settings
backtesting:
  initial_cash: 100000.0
  commission: 0.001
  output_dir: "results"
  save_results: true
  data_cache_dir: "data/cache"

# Data Settings
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA']
  start_date: '2022-01-01'
  end_date: '2023-12-31'
  interval: "1d"
  cache_enabled: true

# Strategy Configuration
strategy:
  name: regime_aware  # Options: regime_aware, sma_crossover
  
  # Strategy-specific parameters
  parameters:
    # Regime-Aware Strategy Parameters
    hazard_rate: 0.01
    change_point_threshold: 0.5
    max_window_length: 252
    risk_aversion: 2.0
    turnover_penalty: 0.001
    min_weight: 0.0
    max_weight: 0.3
    rebalance_frequency: 5
    
    # SMA Crossover Parameters (used if strategy is sma_crossover)
    fast_period: 10
    slow_period: 30
    printlog: false

# Analysis Settings
analysis:
  save_charts: true
  save_reports: true
  chart_dpi: 300

# Risk Management
risk:
  max_position_size: 0.1
  stop_loss_pct: 0.05
  take_profit_pct: 0.15
